$(document).ready(function(){
    $(".design").click(function(){
      $("#design-image").toggle();
      $("#descDesign").toggle();
    });
  });
  $(document).ready(function(){
    $(".development").click(function(){
      $("#development-image").toggle();
      $("#development").toggle();
    });
  });