$(document).ready(function(){
    $(".design").click(function(){
      $("#design-image").toggle();
      $("#descDesign").toggle();
    });
  });
  $(document).ready(function(){
    $(".development").click(function(){
      $("#development-image").toggle();
      $("#development").toggle();
    });
  });
  $(document).ready(function(){
    $(".product").click(function(){
      $("#product-image").toggle();
      $("#product").toggle();
    });
  });

$(document).ready(function(){
  $("#work1").mouseover(function(){
    $("#overlay").show();
  }).mouseout(function(){
    $("#overlay").hide();
  });
});